version: '3.8'

services:
  redis:
    image: redis:6.2.5-alpine
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"  # LOCAL WORKER ulanishi uchun
    networks:
      - tg_bot
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:14-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5434:5432" # LOCAL WORKER ulanishi uchun
    networks:
      - tg_bot

  api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    restart: always
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_LOCAL: ${TELEGRAM_LOCAL}
      TELEGRAM_MAX_FILE_SIZE: 2000
    command: ["--max-file-size=2000", "--local"]
    ports:
      - "8081:8081"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    networks:
      - tg_bot

  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-movie_bot-container}"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    stop_signal: SIGINT
    build:
      context: .
    restart: on-failure
    depends_on:
      - postgres
      - api
    networks:
      - tg_bot
    volumes:
      - .:/app
      - telegram-bot-api-data:/var/lib/telegram-bot-api 


networks:
  tg_bot:
    driver: bridge

volumes:
  pgdata:
  redis-data:
  telegram-bot-api-data: