services:
  worker:
    build: 
      context: .
      dockerfile: worker.Dockerfile
    container_name: movie_bot-worker
    command: celery -A src.app.core.celery_app worker --loglevel=info --concurrency=1
    env_file:
      - .env.local
    volumes:
      - .:/app
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    restart: always
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all    # ← bu muhim: compute,video,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, video]  # ← "video" NVENC uchun kerak

    networks:
      - tg_bot


networks:
  tg_bot:
    driver: bridge

volumes:
  telegram-bot-api-data: