services:
  worker:
    build: .
    container_name: movie_bot-worker
    command: celery -A src.app.core.celery_app worker --loglevel=info --concurrency=2
    env_file:
      - .env
    volumes:
      - .:/app
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    restart: always
    networks:
      - tg_bot

networks:
  tg_bot:
    driver: bridge

volumes:
  telegram-bot-api-data:
